/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visoes;

import Modelos.Consulta;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private VisaoCadastrarConsulta cadastrarConsulta;
    private VisaoDetalhesConsulta detalhesConsulta;
    private Consulta consulta;

   public TelaPrincipal() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_finalizarConsulta = new javax.swing.JButton();
        jButton_excluirConsulta = new javax.swing.JButton();
        jButton_novaConsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tabelaConsultas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(695, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_finalizarConsulta.setText("Finalizar consulta ");
        jButton_finalizarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_finalizarConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_finalizarConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jButton_excluirConsulta.setText("Excluir consulta");
        jButton_excluirConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_excluirConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_excluirConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jButton_novaConsulta.setText("Nova consulta");
        jButton_novaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_novaConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_novaConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jTable_tabelaConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Paciente", "CPF", "Telefone", "Data", "Já era paciente?", "Consulta realizada"
            }
        ));
        jScrollPane1.setViewportView(jTable_tabelaConsultas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 660, 160));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void abrirJanelaDetalhesConsulta() {
        detalhesConsulta = new VisaoDetalhesConsulta(this, true);
        //this.dispose();
        detalhesConsulta.setVisible(true);
     

    }

    private void abrirJanelaNovaConsulta() {
        cadastrarConsulta = new VisaoCadastrarConsulta(consulta,this,true);
        //this.dispose();
        cadastrarConsulta.setVisible(true);
        

    }
    
    



    private void jButton_novaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_novaConsultaActionPerformed
        this.abrirJanelaNovaConsulta();


    }//GEN-LAST:event_jButton_novaConsultaActionPerformed

    private void jButton_finalizarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_finalizarConsultaActionPerformed
    this.abrirJanelaDetalhesConsulta();
    }//GEN-LAST:event_jButton_finalizarConsultaActionPerformed

    private void jButton_excluirConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_excluirConsultaActionPerformed
        this.removeLinhaTabelaElista();
    }//GEN-LAST:event_jButton_excluirConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new TelaPrincipal().setVisible(true);

            }
        });

    }

    public void recebeDadosRemocao(JTable tabela, List<Consulta> consultas) {
        int rowIndex = tabela.getSelectedRow();
        if (rowIndex != -1) {
            // Remover a consulta correspondente na lista
            consultas.remove(rowIndex);

            // Atualizar o modelo da tabela
            DefaultTableModel model = (DefaultTableModel) tabela.getModel();
            model.removeRow(rowIndex);
        } else {
            // Tratar caso nenhuma linha esteja selecionada
            System.out.println("Nenhuma linha selecionada.");
        }
    }

    public void removeLinhaTabelaElista() {
        JTable tabela = this.getjTable_tabelaConsultas();
        List<Consulta> lista = consulta.getConsultas();
        this.recebeDadosRemocao(tabela, lista);
    }

    public JTable getjTable_tabelaConsultas() {
        return jTable_tabelaConsultas;
    }

    public void setjTable_tabelaConsultas(JTable jTable_tabelaConsultas) {
        this.jTable_tabelaConsultas = jTable_tabelaConsultas;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_excluirConsulta;
    private javax.swing.JButton jButton_finalizarConsulta;
    private javax.swing.JButton jButton_novaConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_tabelaConsultas;
    // End of variables declaration//GEN-END:variables
}
