/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visoes;

import Modelos.Consulta;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class VisaoDetalhesConsulta extends javax.swing.JDialog {

    private Consulta consulta;
    private TelaPrincipal telaPrincipal;

    /**
     * Creates new form VisaoDetalhesConsulta
     */
    public VisaoDetalhesConsulta(TelaPrincipal telaPrincipal, boolean modal) {
        super(telaPrincipal, modal);
        this.telaPrincipal = telaPrincipal;
        initComponents();
        this.verificarConsultaRealizada();
        this.getjCheckBoxConsultaRealizada().setSelected(true);

        // telaPrincipal = new TelaPrincipal();
        // consulta = new Consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTtitulo = new javax.swing.JLabel();
        jCheckBoxConsultaRealizada = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReceitaObservacoes = new javax.swing.JTextArea();
        jButtonFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTtitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTtitulo.setText("Detelhes da consulta");
        getContentPane().add(jLabelTtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 290, -1));

        jCheckBoxConsultaRealizada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxConsultaRealizada.setText("Consulta realizada");
        jCheckBoxConsultaRealizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxConsultaRealizadaActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxConsultaRealizada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jTextAreaReceitaObservacoes.setColumns(20);
        jTextAreaReceitaObservacoes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaReceitaObservacoes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 570, 190));

        jButtonFinalizar.setText("Finalizar");
        jButtonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void verificarConsultaRealizada() {
        int linhaSelecionada = telaPrincipal.getjTable_tabelaConsultas().getSelectedRow();
        if (linhaSelecionada != -1) {  // se houver uma linha selecionada
            String consultaRealizada = (String) telaPrincipal.getjTable_tabelaConsultas().getValueAt(linhaSelecionada, 5);
            if (consultaRealizada == null || consultaRealizada.isEmpty()) {
                this.getjButtonFinalizar().setVisible(true);
            } else {
                this.getjButtonFinalizar().setVisible(false);
            }
        }
    }

    public void finalizarConsulta() {

        int linhaSelecionada = telaPrincipal.getjTable_tabelaConsultas().getSelectedRow();
        if (linhaSelecionada != -1) {  // se houver uma linha selecionada
            boolean consultaRealizada = this.getjCheckBoxConsultaRealizada().isSelected();
            if (consultaRealizada) {
                // Atualiza o modelo do JTable
                telaPrincipal.getjTable_tabelaConsultas().setValueAt("Consulta realizada", linhaSelecionada, 5);

                // Atualiza a lista
                consulta.getConsultas().get(linhaSelecionada).setConsultaRealizada("Consulta realizada");

                // Redefine a caixa de seleção para o estado não selecionado
                this.getjCheckBoxConsultaRealizada().setSelected(false);
            } else {
                JOptionPane.showMessageDialog(null, "A consulta não foi realizada!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma consulta selecionada!");
        }
    }


    private void jCheckBoxConsultaRealizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxConsultaRealizadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxConsultaRealizadaActionPerformed

    private void jButtonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarActionPerformed
        this.finalizarConsulta();
    }//GEN-LAST:event_jButtonFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoDetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoDetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoDetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoDetalhesConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPrincipal minhaTelaPrincipal = new TelaPrincipal();
                VisaoDetalhesConsulta dialog = new VisaoDetalhesConsulta(minhaTelaPrincipal, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });
    }

    public JCheckBox getjCheckBoxConsultaRealizada() {
        return jCheckBoxConsultaRealizada;
    }

    public void setjCheckBoxConsultaRealizada(JCheckBox jCheckBoxConsultaRealizada) {
        this.jCheckBoxConsultaRealizada = jCheckBoxConsultaRealizada;
    }

    public JButton getjButtonFinalizar() {
        return jButtonFinalizar;
    }

    public void setjButtonFinalizar(JButton jButtonFinalizar) {
        this.jButtonFinalizar = jButtonFinalizar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFinalizar;
    private javax.swing.JCheckBox jCheckBoxConsultaRealizada;
    private javax.swing.JLabel jLabelTtitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaReceitaObservacoes;
    // End of variables declaration//GEN-END:variables
}
