/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Visoes;

import Modelos.Consulta;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class VisaoCadastrarConsulta extends javax.swing.JDialog {

    private final TelaPrincipal telaPrincipal;
    private static Consulta consulta;

   public VisaoCadastrarConsulta(Consulta consulta, TelaPrincipal telaPrincipal, java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

        this.telaPrincipal = telaPrincipal;
        this.consulta = consulta;
    }
    
    public VisaoCadastrarConsulta(Consulta consulta, TelaPrincipal telaPrincipal, boolean modal) {
    super(telaPrincipal, modal);
    
      initComponents();
    this.telaPrincipal = telaPrincipal;
    this.consulta = consulta;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelSubtitulo = new javax.swing.JLabel();
        Subtitulo3 = new javax.swing.JLabel();
        jLabelSubititulo1 = new javax.swing.JLabel();
        jLabelSubtitulo2 = new javax.swing.JLabel();
        jCheckBoxJaEpaciente = new javax.swing.JCheckBox();
        jButtonCadastrar = new javax.swing.JButton();
        jFormattedTextFieldDataConsulta = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jTextFieldNomePaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo.setText("Cadastrar Consulta");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 25, 301, 43));

        jLabelSubtitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSubtitulo.setText("Nome do paciente:");
        getContentPane().add(jLabelSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, -1));

        Subtitulo3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Subtitulo3.setText("Data consulta:");
        getContentPane().add(Subtitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 226, -1, -1));

        jLabelSubititulo1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSubititulo1.setText("Telefone:");
        getContentPane().add(jLabelSubititulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 140, -1, -1));

        jLabelSubtitulo2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSubtitulo2.setText("Cpf:");
        getContentPane().add(jLabelSubtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 185, -1, -1));

        jCheckBoxJaEpaciente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCheckBoxJaEpaciente.setText("Já é pacinente");
        getContentPane().add(jCheckBoxJaEpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 280, 110, -1));

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 332, 110, -1));

        try {
            jFormattedTextFieldDataConsulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldDataConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, 30));

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)###-##-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextFieldTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 200, 30));

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 200, 30));
        getContentPane().add(jTextFieldNomePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefoneActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        this.inserirConsultaLista();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed
    public Consulta criarConsulta() {
        String nomePaciente = this.getjTextFieldNomePaciente().getText();
        String telefone = this.getjFormattedTextFieldTelefone().getText();
        String cpf = this.getjFormattedTextFieldCpf().getText();
        String dataConsulta = this.getjFormattedTextFieldDataConsulta().getText();
        String jaPaciente = "";
        if (this.getjCheckBoxJaEpaciente().isSelected()) {
            jaPaciente = "sim";
        } else {
            jaPaciente = "não";
        }
        //String consultaRealizada = "";
        if (!telefone.isEmpty() && !nomePaciente.isEmpty() && !cpf.isEmpty() && !dataConsulta.isEmpty()) {
            Consulta consultaCriada = new Consulta(nomePaciente, telefone, cpf, dataConsulta, jaPaciente);
            return consultaCriada;
        } else {

            return null;
        }
    }

    public void inserirConsultaLista() {
    Consulta consultaCriada = this.criarConsulta();
    if (consultaCriada != null) {
        // Verificando se a variável consulta foi inicializada
        if (consulta == null) {
            // inicializar a variável 'consulta'
            // Substituir Consulta pelo tipo real de 'consulta'
            consulta = new Consulta();
        }
        consulta.addConsulta(consultaCriada);
        //JOptionPane.showMessageDialog(null, consulta.toString());
        List<Consulta> listaConsulta = Consulta.getConsultas();
        JTable tabela = telaPrincipal.getjTable_tabelaConsultas();
        this.preencherTabela(listaConsulta, tabela);
        telaPrincipal.setVisible(true);
        this.dispose();

    } else {
        JOptionPane.showMessageDialog(null, "Consulta em branco!");
    }
}


    public void preencherTabela(List<Consulta> listaConsultas, JTable tabela) {
        // Criamos um modelo padrão para o JTable
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();

        // Limpa a tabela antes de preencher com novos dados
        modelo.setRowCount(0);

        //  preenche o modelo com os dados das consultas
        for (Consulta consulta : listaConsultas) {
            modelo.addRow(new Object[]{
                consulta.getNome(),
                consulta.getTelefone(),
                consulta.getCpf(),
                consulta.getDataConsulta(),
                consulta.getJaEpaciente(),
                consulta.getConsultaRealizada()
                    
            });
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoCadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoCadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoCadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoCadastrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaPrincipal minhaTelaPrincipal = new TelaPrincipal();
                //Consulta minhaConsulta = new Consulta();
                VisaoCadastrarConsulta dialog = new VisaoCadastrarConsulta(consulta, minhaTelaPrincipal, new javax.swing.JFrame(), true);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JCheckBox getjCheckBoxJaEpaciente() {
        return jCheckBoxJaEpaciente;
    }

    public void setjCheckBoxJaEpaciente(JCheckBox jCheckBoxJaEpaciente) {
        this.jCheckBoxJaEpaciente = jCheckBoxJaEpaciente;
    }

    public JFormattedTextField getjFormattedTextFieldCpf() {
        return jFormattedTextFieldCpf;
    }

    public void setjFormattedTextFieldCpf(JFormattedTextField jFormattedTextFieldCpf) {
        this.jFormattedTextFieldCpf = jFormattedTextFieldCpf;
    }

    public JFormattedTextField getjFormattedTextFieldDataConsulta() {
        return jFormattedTextFieldDataConsulta;
    }

    public void setjFormattedTextFieldDataConsulta(JFormattedTextField jFormattedTextFieldDataConsulta) {
        this.jFormattedTextFieldDataConsulta = jFormattedTextFieldDataConsulta;
    }

    public JFormattedTextField getjFormattedTextFieldTelefone() {
        return jFormattedTextFieldTelefone;
    }

    public void setjFormattedTextFieldTelefone(JFormattedTextField jFormattedTextFieldTelefone) {
        this.jFormattedTextFieldTelefone = jFormattedTextFieldTelefone;
    }

    public JTextField getjTextFieldNomePaciente() {
        return jTextFieldNomePaciente;
    }

    public void setjTextFieldNomePaciente(JTextField jTextFieldNomePaciente) {
        this.jTextFieldNomePaciente = jTextFieldNomePaciente;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Subtitulo3;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JCheckBox jCheckBoxJaEpaciente;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataConsulta;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabelSubititulo1;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelSubtitulo2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldNomePaciente;
    // End of variables declaration//GEN-END:variables
}
